//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdditionalCharge
    {
        public int Id { get; set; }
        public string AddCharge { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public double Cost { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> OrderId { get; set; }
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public Nullable<double> TotalCost { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
