//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalCharge
    {
        public int Id { get; set; }
        public string AddCharge { get; set; }
        public double Cost { get; set; }
        public double Qty { get; set; }
        public Nullable<int> OrderId { get; set; }
        public double TotalCost { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
