//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AditionalCharge
    {
        public string id { get; set; }
        public int OrderItemId { get; set; }
        public string ChargeType { get; set; }
        public int Cost { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
