//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Code { get; set; }
        public Nullable<int> CodeNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string status { get; set; }
        public string remark { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
