//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_stwfmEntities : DbContext
    {
        public DB_stwfmEntities()
            : base("name=DB_stwfmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DataAudit> DataAudits { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<LoginAudit> LoginAudits { get; set; }
        public virtual DbSet<OrderTracking> OrderTrackings { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<OrderWayForward> OrderWayForwards { get; set; }
        public virtual DbSet<PaperQuality> PaperQualities { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<QuoteTermDetail> QuoteTermDetails { get; set; }
        public virtual DbSet<OrderTermDetail> OrderTermDetails { get; set; }
        public virtual DbSet<QuoteTerm> QuoteTerms { get; set; }
        public virtual DbSet<Visibility> Visibilities { get; set; }
        public virtual DbSet<WarrantyPeriod> WarrantyPeriods { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Fasia> Fasias { get; set; }
        public virtual DbSet<Framework> Frameworks { get; set; }
        public virtual DbSet<Installation> Installations { get; set; }
        public virtual DbSet<Lettering> Letterings { get; set; }
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<QuoteItem> QuoteItems { get; set; }
        public virtual DbSet<Illumination> Illuminations { get; set; }
        public virtual DbSet<DeliveryType> DeliveryTypes { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<AdditionalCharge> AdditionalCharges { get; set; }
        public virtual DbSet<OrderAttachment> OrderAttachments { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<InstallationAttachment> InstallationAttachments { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<OrderMaterial> OrderMaterials { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierType> SupplierTypes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
