//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTracking
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> FromDivisionId { get; set; }
        public Nullable<int> ToDivisionId { get; set; }
        public Nullable<System.DateTime> TransferredDate { get; set; }
        public string TransferredBy { get; set; }
        public string Comment { get; set; }
        public Nullable<int> FactoryStatusId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Division Division { get; set; }
        public virtual Division Division1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
