//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteItem
    {
        public int Id { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public Nullable<int> CatgoryId { get; set; }
        public string Size { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
